spring.application.name=reto

spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/${DB_SERVICE:FREEPDB1}
spring.datasource.username=${DB_USER:reto}
spring.datasource.password=${DB_PASSWORD:reto123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
